const MAX_POKEMON=809;
const GEN_RANGES={1:[1,151],2:[152,251],3:[252,386],4:[387,493],5:[494,649],6:[650,721],7:[722,809]};
const STORAGE_KEY='nuzlocke-tracker-v3';
const GAME_OPTIONS={1:['Pokémon Rojo','Pokémon Azul','Pokémon Amarillo'],2:['Pokémon Oro','Pokémon Plata','Pokémon Cristal'],3:['Pokémon Rubí','Pokémon Zafiro','Pokémon Esmeralda','Pokémon Rojo Fuego','Pokémon Verde Hoja'],4:['Pokémon Diamante','Pokémon Perla','Pokémon Platino','Pokémon HeartGold','Pokémon SoulSilver'],5:['Pokémon Negro','Pokémon Blanco','Pokémon Negro 2','Pokémon Blanco 2'],6:['Pokémon X','Pokémon Y','Pokémon Rubí Omega','Pokémon Zafiro Alfa'],7:['Pokémon Sol','Pokémon Luna','Pokémon Ultrasol','Pokémon Ultraluna'];};
let pokemon=[];let games=JSON.parse(localStorage.getItem(STORAGE_KEY)||'[]');let selectedGame=null;let selectedBoss=null;let selectedBossType='Líder de gimnasio';let pendingImage='';
const $=id=>document.getElementById(id),slug=id=>String(id).padStart(3,'0'),sprite=id=>`https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/${id}.png`;
function saveAll(){try{localStorage.setItem(STORAGE_KEY,JSON.stringify(games));return true}catch(e){alert('No se pudo guardar. La imagen es demasiado grande para el almacenamiento del navegador.');return false}}
function genOf(id){for(const[g,[a,b]]of Object.entries(GEN_RANGES))if(id>=a&&id<=b)return Number(g);return 0}function cap(s){return String(s).split('-').map(x=>x.charAt(0).toUpperCase()+x.slice(1)).join('-')}function escapeHtml(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}function typeIcon(t){return{'Líder de gimnasio':'🥇','Alto Mando':'👑','Rival':'⚔️','Equipo enemigo':'☠️'}[t]||'👤'}
function openGameModal(){fillGameOptions();$('customGameName').value='';$('gameModal').hidden=false}function closeGameModal(){$('gameModal').hidden=true}
function fillGameOptions(){const g=$('gameGeneration').value,arr=GAME_OPTIONS[g]||[];$('gamePreset').innerHTML=arr.map(x=>`<option value="${escapeHtml(x)}">${escapeHtml(x)}</option>`).join('')} 
function createGame(){const name=($('customGameName').value.trim()||$('gamePreset').value||'Mi Nuzlocke').trim();games.push({name,bosses:[]});saveAll();closeGameModal();selectGame(games.length-1)}
function selectGame(i){selectedGame=i;selectedBoss=null;$('gamesEmpty').hidden=true;$('gameEditor').hidden=false;renderGames();renderGame()}
function renderGames(){$('gameCount').textContent=games.length;$('gameList').innerHTML='';games.forEach((g,i)=>{const b=document.createElement('button');b.className='boss-button'+(selectedGame===i?' active':'');b.innerHTML=`<strong>${escapeHtml(g.name||`Juego ${i+1}`)}</strong><small>${g.bosses.length} Boss${g.bosses.length===1?'':'es'}</small>`;b.onclick=()=>selectGame(i);$('gameList').appendChild(b)})}
function renderGame(){const g=games[selectedGame];if(!g)return;$('pageTitle').textContent=g.name;$('gameName').value=g.name;$('bossCount').textContent=g.bosses.length;$('bossListInside').innerHTML='';$('noBosses').hidden=!!g.bosses.length;g.bosses.forEach((b,i)=>{const c=document.createElement('article');c.className='boss-card';const art=b.image?`<img src="${b.image}" alt="Diseño de ${escapeHtml(b.name)}">`:`<div class="boss-placeholder">${typeIcon(b.type)}</div>`;c.innerHTML=`<div class="boss-art">${art}</div><div class="boss-card-body"><span class="type-tag">${typeIcon(b.type)} ${escapeHtml(b.type)}</span><h3>${escapeHtml(b.name||`Boss ${i+1}`)}</h3><p>${b.team.length}/6 Pokémon</p><button class="secondary open-boss">Abrir Boss</button></div>`;c.querySelector('.open-boss').onclick=()=>openBoss(i);$('bossListInside').appendChild(c)})}
function openBoss(i){selectedBoss=i;const g=games[selectedGame],b=g.bosses[i];$('gameEditor').hidden=true;$('pageTitle').textContent=`${g.name} · ${b.name}`;const e=document.createElement('div');e.id='bossDetail';e.className='boss-detail';e.innerHTML=`<div class="editor-head"><div><button id="backGame" class="back">← Volver a ${escapeHtml(g.name)}</button><span class="type-tag big">${typeIcon(b.type)} ${escapeHtml(b.type)}</span><label>Nombre del Boss</label><input id="bossName" maxlength="60" value="${escapeHtml(b.name||'Boss')}"></div><button id="deleteBoss" class="danger">Eliminar Boss</button></div><div class="boss-design-row">${b.image?`<img src="${b.image}" alt="Diseño del Boss">`:''}<div><strong>Diseño del Boss</strong><p>${b.image?'Imagen adjunta.':'Sin imagen adjunta.'}</p><button id="changeBossImage" class="secondary">Adjuntar/cambiar imagen</button><input id="detailImage" type="file" accept="image/*" hidden></div></div><div class="toolbar"><input id="pokemonSearch" type="search" placeholder="Buscar Pokémon (Gen 1–7, #001–#809)..."><select id="generationFilter"><option value="all">Generaciones 1–7</option><option value="1">Gen 1 · Kanto</option><option value="2">Gen 2 · Johto</option><option value="3">Gen 3 · Hoenn</option><option value="4">Gen 4 · Sinnoh</option><option value="5">Gen 5 · Teselia</option><option value="6">Gen 6 · Kalos</option><option value="7">Gen 7 · Alola</option></select></div><div id="pokemonResults" class="pokemon-results"></div><h3>Equipo <span id="teamCount">0/6</span></h3><div id="team" class="team"></div><button id="saveBoss" class="primary save">Guardar Boss</button>`;$('gameEditor').after(e);$('backGame').onclick=()=>{e.remove();$('gameEditor').hidden=false;$('pageTitle').textContent=g.name;renderGame()};$('bossName').oninput=x=>{b.name=x.target.value;saveAll();renderGames();$('pageTitle').textContent=`${g.name} · ${b.name}`};$('deleteBoss').onclick=()=>{if(confirm('¿Eliminar este Boss?')){g.bosses.splice(i,1);saveAll();e.remove();$('gameEditor').hidden=false;$('pageTitle').textContent=g.name;renderGame()}};$('saveBoss').onclick=()=>{if(saveAll()){$('saveBoss').textContent='Guardado ✓';setTimeout(()=>$('saveBoss').textContent='Guardar Boss',1000)}};$('changeBossImage').onclick=()=>$('detailImage').click();$('detailImage').onchange=x=>readImage(x.target.files[0],data=>{b.image=data;saveAll();e.remove();openBoss(i)});$('pokemonSearch').oninput=renderPokemon;$('generationFilter').onchange=renderPokemon;renderEditorTeam();renderPokemon()}
function renderEditorTeam(){const b=games[selectedGame].bosses[selectedBoss];$('teamCount').textContent=`${b.team.length}/6`;$('team').innerHTML='';if(!b.team.length){$('team').innerHTML='<div class="empty-team">Añade Pokémon desde el buscador de arriba.</div>';return}b.team.forEach((m,i)=>{const p=pokemon.find(x=>x.id===m.id)||{id:m.id,name:m.name};const c=document.createElement('article');c.className='team-card';c.innerHTML=`<img class="sprite" src="${sprite(p.id)}" alt=""><div class="team-main"><div class="team-title"><strong class="poke-name">#${slug(p.id)} ${cap(p.name)}</strong><button class="remove">×</button></div><div class="fields"><label>Nivel<input class="level" type="number" min="1" max="100" value="${m.level||50}"></label><label>Habilidad<input class="ability" value="${escapeHtml(m.ability||'')}" placeholder="Habilidad"></label><label>Objeto<input class="item" value="${escapeHtml(m.item||'')}" placeholder="Objeto"></label><label>Movimientos<input class="moves" value="${escapeHtml(m.moves||'')}" placeholder="Movimiento 1, Movimiento 2, ..."></label></div></div>`;c.querySelector('.remove').onclick=()=>{b.team.splice(i,1);saveAll();renderEditorTeam();renderPokemon()};['level','ability','item','moves'].forEach(k=>c.querySelector('.'+k).oninput=x=>{m[k]=x.target.value;saveAll()});$('team').appendChild(c)})}
async function loadPokemon(){try{const r=await fetch(`https://pokeapi.co/api/v2/pokemon?limit=${MAX_POKEMON}`),d=await r.json();pokemon=d.results.map((p,i)=>({id:i+1,name:p.name}))}catch(e){pokemon=Array.from({length:MAX_POKEMON},(_,i)=>({id:i+1,name:`Pokémon #${slug(i+1)}`}))}if($('pokemonResults'))renderPokemon()}
function renderPokemon(){const box=$('pokemonResults');if(!box)return;const q=$('pokemonSearch').value.trim().toLowerCase(),gf=$('generationFilter').value,b=games[selectedGame].bosses[selectedBoss];const list=pokemon.filter(p=>(!q||p.name.includes(q)||String(p.id)===q.replace(/^#/,'')||slug(p.id)===q.replace(/^#/,''))&&(gf==='all'||String(genOf(p.id))===gf)).slice(0,60);box.innerHTML='';if(!list.length){box.innerHTML='<div class="empty-team">No se encontraron Pokémon.</div>';return}list.forEach(p=>{const inTeam=b.team.some(x=>x.id===p.id),btn=document.createElement('button');btn.className='poke-option';btn.disabled=inTeam||b.team.length>=6;btn.innerHTML=`<img src="${sprite(p.id)}"><span><strong>#${slug(p.id)} ${cap(p.name)}</strong><em>Gen ${genOf(p.id)}${inTeam?' · En equipo':''}</em></span>`;btn.onclick=()=>addPokemon(p.id);box.appendChild(btn)})}
function addPokemon(id){const b=games[selectedGame].bosses[selectedBoss];if(b.team.length>=6||b.team.some(x=>x.id===id))return;const p=pokemon.find(x=>x.id===id);b.team.push({id,name:p?.name||`Pokemon #${id}`,level:50,ability:'',item:'',moves:''});saveAll();renderEditorTeam();renderPokemon()}
function openCreateBoss(){selectedBossType='Líder de gimnasio';pendingImage='';$('modalBossName').value='';$('bossImage').value='';$('imagePreview').textContent='Sin imagen seleccionada';document.querySelectorAll('#bossTypeChoices button').forEach(x=>x.classList.toggle('selected',x.dataset.type===selectedBossType));$('bossModal').hidden=false}
function closeCreateBoss(){$('bossModal').hidden=true}
function readImage(file,cb){if(!file)return;if(!file.type.startsWith('image/')){alert('Selecciona una imagen válida.');return}const r=new FileReader();r.onload=()=>{const img=new Image();img.onload=()=>{const max=900,scale=Math.min(1,max/Math.max(img.width,img.height)),c=document.createElement('canvas');c.width=Math.max(1,Math.round(img.width*scale));c.height=Math.max(1,Math.round(img.height*scale));c.getContext('2d').drawImage(img,0,0,c.width,c.height);cb(c.toDataURL('image/jpeg',.78))};img.src=r.result};r.readAsDataURL(file)}
function confirmCreateBoss(){if(selectedGame===null){alert('Primero elige un juego.');return}const g=games[selectedGame],name=$('modalBossName').value.trim()||`Boss ${g.bosses.length+1}`;g.bosses.push({name,type:selectedBossType,image:pendingImage,team:[]});if(saveAll()){closeCreateBoss();renderGame();openBoss(g.bosses.length-1)}}
$('newGame').onclick=openGameModal;$('emptyNewGame').onclick=openGameModal;$('gameGeneration').onchange=fillGameOptions;$('closeGameModal').onclick=closeGameModal;$('cancelGame').onclick=closeGameModal;$('confirmGame').onclick=createGame;$('gameModal').addEventListener('click',e=>{if(e.target===$('gameModal'))closeGameModal()});$('gameName').oninput=e=>{if(selectedGame!==null){games[selectedGame].name=e.target.value;saveAll();renderGames();$('pageTitle').textContent=e.target.value}};$('deleteGame').onclick=()=>{if(selectedGame===null)return;if(confirm('¿Eliminar este juego y todos sus Bosses?')){games.splice(selectedGame,1);saveAll();selectedGame=null;$('gameEditor').hidden=true;$('gamesEmpty').hidden=false;$('pageTitle').textContent='Elige tu juego';renderGames()}};$('newBoss').onclick=openCreateBoss;$('closeBossModal').onclick=closeCreateBoss;$('cancelBoss').onclick=closeCreateBoss;$('confirmBoss').onclick=confirmCreateBoss;document.querySelectorAll('#bossTypeChoices button').forEach(btn=>btn.onclick=()=>{selectedBossType=btn.dataset.type;document.querySelectorAll('#bossTypeChoices button').forEach(x=>x.classList.toggle('selected',x===btn))});$('bossImage').onchange=e=>readImage(e.target.files[0],data=>{pendingImage=data;$('imagePreview').innerHTML=`<img src="${data}" alt="Vista previa">`});$('bossModal').addEventListener('click',e=>{if(e.target===$('bossModal'))closeCreateBoss()});
fillGameOptions();renderGames();if(games.length)selectGame(0);else{$('gamesEmpty').hidden=false;$('gameEditor').hidden=true}loadPokemon();