const MAX_POKEMON=809;
const GEN_RANGES={1:[1,151],2:[152,251],3:[252,386],4:[387,493],5:[494,649],6:[650,721],7:[722,809]};
const GAMES={1:['Pokémon Rojo','Pokémon Azul','Pokémon Amarillo'],2:['Pokémon Oro','Pokémon Plata','Pokémon Cristal'],3:['Pokémon Rubí','Pokémon Zafiro','Pokémon Esmeralda','Pokémon Rojo Fuego','Pokémon Verde Hoja'],4:['Pokémon Diamante','Pokémon Perla','Pokémon Platino','Pokémon HeartGold','Pokémon SoulSilver'],5:['Pokémon Negro','Pokémon Blanco','Pokémon Negro 2','Pokémon Blanco 2'],6:['Pokémon X','Pokémon Y','Pokémon Rubí Omega','Pokémon Zafiro Alfa'],7:['Pokémon Sol','Pokémon Luna','Pokémon Ultrasol','Pokémon Ultraluna']};
const KEY='nuzlocke-tracker-v4';let games=JSON.parse(localStorage.getItem(KEY)||'[]'),pokemon=[],game=null,boss=null,bossType='Líder de gimnasio',image='';
const $=id=>document.getElementById(id),pad=n=>String(n).padStart(3,'0'),img=n=>`https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/${n}.png`,esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),cap=s=>String(s).split('-').map(x=>x[0]?.toUpperCase()+x.slice(1)).join('-');
function save(){try{localStorage.setItem(KEY,JSON.stringify(games));return true}catch(e){alert('No se pudo guardar. Prueba con una imagen más pequeña.');return false}}
function gen(n){for(const[g,r]of Object.entries(GEN_RANGES))if(n>=r[0]&&n<=r[1])return +g;return 0}function icon(t){return {'Líder de gimnasio':'🥇','Alto Mando':'👑','Rival':'⚔️','Equipo enemigo':'☠️'}[t]||'👤'}
function showGameModal(){fillGames();$('customGameName').value='';$('gameModal').hidden=false}function closeGame(){ $('gameModal').hidden=true }
function fillGames(){const a=GAMES[$('gameGeneration').value]||[];$('gamePreset').innerHTML=a.map(x=>`<option value="${esc(x)}">${esc(x)}</option>`).join('')}
function addGame(){const name=$('customGameName').value.trim()||$('gamePreset').value;if(!name)return;games.push({name,bosses:[]});save();closeGame();selectGame(games.length-1)}
function renderGames(){ $('gameCount').textContent=games.length;$('gameList').innerHTML='';games.forEach((g,i)=>{const b=document.createElement('button');b.className='boss-button '+(game===i?'active':'');b.innerHTML=`<strong>${esc(g.name)}</strong><small>${g.bosses.length} Boss${g.bosses.length===1?'':'es'}</small>`;b.onclick=()=>selectGame(i);$('gameList').appendChild(b)})}
function selectGame(i){game=i;boss=null;$('gamesEmpty').hidden=true;$('gameEditor').hidden=false;renderGames();renderGame()}
function renderGame(){const g=games[game];$('pageTitle').textContent=g.name;$('gameName').value=g.name;$('bossCount').textContent=g.bosses.length;$('bossListInside').innerHTML='';$('noBosses').hidden=!!g.bosses.length;g.bosses.forEach((b,i)=>{const c=document.createElement('article');c.className='boss-card';c.innerHTML=`<div class="boss-art">${b.image?`<img src="${b.image}" alt="">`:`<div class="boss-placeholder">${icon(b.type)}</div>`}</div><div class="boss-card-body"><span class="type-tag">${icon(b.type)} ${esc(b.type)}</span><h3>${esc(b.name)}</h3><p>${b.team.length}/6 Pokémon</p><button class="secondary open">Abrir Boss</button></div>`;c.querySelector('.open').onclick=()=>openBoss(i);$('bossListInside').appendChild(c)})}
function openBoss(i){boss=i;const b=games[game].bosses[i],g=games[game];$('gameEditor').hidden=true;$('pageTitle').textContent=`${g.name} · ${b.name}`;const e=document.createElement('div');e.id='bossDetail';e.className='boss-detail';e.innerHTML=`<div class="editor-head"><div><button id="back" class="back">← Volver</button><span class="type-tag big">${icon(b.type)} ${esc(b.type)}</span><label>Nombre del Boss</label><input id="bossName" value="${esc(b.name)}" maxlength="60"></div><button id="delBoss" class="danger">Eliminar Boss</button></div><div class="boss-design-row">${b.image?`<img src="${b.image}" alt="Diseño">`:''}<div><strong>Diseño del Boss</strong><p>${b.image?'Imagen adjunta.':'Sin imagen.'}</p><button id="changeImage" class="secondary">Adjuntar/cambiar imagen</button><input id="detailImage" type="file" accept="image/*" hidden></div></div><div class="toolbar"><input id="pokemonSearch" type="search" placeholder="Buscar Pokémon #001–#809..."><select id="generationFilter"><option value="all">Generaciones 1–7</option><option value="1">Gen 1 · Kanto</option><option value="2">Gen 2 · Johto</option><option value="3">Gen 3 · Hoenn</option><option value="4">Gen 4 · Sinnoh</option><option value="5">Gen 5 · Teselia</option><option value="6">Gen 6 · Kalos</option><option value="7">Gen 7 · Alola</option></select></div><div id="pokemonResults" class="pokemon-results"></div><h3>Equipo <span id="teamCount">0/6</span></h3><div id="team" class="team"></div><button id="saveBoss" class="primary save">Guardar Boss</button>`;$('gameEditor').after(e);$('back').onclick=()=>{e.remove();$('gameEditor').hidden=false;renderGame()};$('bossName').oninput=x=>{b.name=x.target.value;save();$('pageTitle').textContent=`${g.name} · ${b.name}`};$('delBoss').onclick=()=>{if(confirm('¿Eliminar este Boss?')){g.bosses.splice(i,1);save();e.remove();$('gameEditor').hidden=false;renderGame()}};$('saveBoss').onclick=()=>{if(save()){$('saveBoss').textContent='Guardado ✓';setTimeout(()=>{$('saveBoss').textContent='Guardar Boss'},900)}};$('changeImage').onclick=()=>$('detailImage').click();$('detailImage').onchange=x=>readImage(x.target.files[0],d=>{b.image=d;if(save()){e.remove();openBoss(i)}});$('pokemonSearch').oninput=renderPokemon;$('generationFilter').onchange=renderPokemon;renderTeam();renderPokemon()}
function renderTeam(){const b=games[game].bosses[boss];$('teamCount').textContent=`${b.team.length}/6`;$('team').innerHTML=b.team.length?'':'<div class="empty-team">Añade Pokémon desde el buscador.</div>';b.team.forEach((m,i)=>{const p=pokemon.find(x=>x.id===m.id)||m,c=document.createElement('article');c.className='team-card';c.innerHTML=`<img class="sprite" src="${img(p.id)}"><div class="team-main"><div class="team-title"><strong>#${pad(p.id)} ${cap(p.name)}</strong><button class="remove">×</button></div><div class="fields"><label>Nivel<input class="level" type="number" min="1" max="100" value="${m.level||50}"></label><label>Habilidad<input class="ability" value="${esc(m.ability||'')}"></label><label>Objeto<input class="item" value="${esc(m.item||'')}"></label><label>Movimientos<input class="moves" value="${esc(m.moves||'')}"></label></div></div>`;c.querySelector('.remove').onclick=()=>{b.team.splice(i,1);save();renderTeam();renderPokemon()};['level','ability','item','moves'].forEach(k=>c.querySelector('.'+k).oninput=x=>{m[k]=x.target.value;save()});$('team').appendChild(c)})}
async function load(){try{const r=await fetch(`https://pokeapi.co/api/v2/pokemon?limit=${MAX_POKEMON}`),d=await r.json();pokemon=d.results.map((x,i)=>({id:i+1,name:x.name}))}catch(e){pokemon=Array.from({length:MAX_POKEMON},(_,i)=>({id:i+1,name:`Pokémon #${pad(i+1)}`}))}if($('pokemonResults'))renderPokemon()}
function renderPokemon(){const box=$('pokemonResults');if(!box)return;const q=$('pokemonSearch').value.toLowerCase().trim(),f=$('generationFilter').value,b=games[game].bosses[boss],list=pokemon.filter(p=>(!q||p.name.includes(q)||String(p.id)===q.replace('#','')||pad(p.id)===q.replace('#',''))&&(f==='all'||gen(p.id)==f)).slice(0,60);box.innerHTML=list.length?'':'<div class="empty-team">No se encontraron Pokémon.</div>';list.forEach(p=>{const used=b.team.some(x=>x.id===p.id),x=document.createElement('button');x.className='poke-option';x.disabled=used||b.team.length>=6;x.innerHTML=`<img src="${img(p.id)}"><span><strong>#${pad(p.id)} ${cap(p.name)}</strong><em>Gen ${gen(p.id)}${used?' · En equipo':''}</em></span>`;x.onclick=()=>addPokemon(p.id);box.appendChild(x)})}
function addPokemon(id){const b=games[game].bosses[boss];if(b.team.length>=6||b.team.some(x=>x.id===id))return;const p=pokemon.find(x=>x.id===id);b.team.push({id,name:p.name,level:50,ability:'',item:'',moves:''});save();renderTeam();renderPokemon()}
function showBossModal(){bossType='Líder de gimnasio';image='';$('modalBossName').value='';$('bossImage').value='';$('imagePreview').textContent='Sin imagen seleccionada';document.querySelectorAll('#bossTypeChoices button').forEach(x=>x.classList.toggle('selected',x.dataset.type===bossType));$('bossModal').hidden=false}function closeBoss(){ $('bossModal').hidden=true }
function readImage(file,cb){if(!file)return;if(!file.type.startsWith('image/'))return alert('Selecciona una imagen.');const r=new FileReader();r.onload=()=>{const im=new Image();im.onload=()=>{const max=900,s=Math.min(1,max/Math.max(im.width,im.height)),c=document.createElement('canvas');c.width=Math.max(1,Math.round(im.width*s));c.height=Math.max(1,Math.round(im.height*s));c.getContext('2d').drawImage(im,0,0,c.width,c.height);cb(c.toDataURL('image/jpeg',.78))};im.src=r.result};r.readAsDataURL(file)}
function createBoss(){if(game===null)return alert('Primero elige un juego.');const g=games[game];g.bosses.push({name:$('modalBossName').value.trim()||`Boss ${g.bosses.length+1}`,type:bossType,image,team:[]});if(save()){closeBoss();renderGame();openBoss(g.bosses.length-1)}}
$('newGame').onclick=showGameModal;$('emptyNewGame').onclick=showGameModal;$('gameGeneration').onchange=fillGames;$('closeGameModal').onclick=closeGame;$('cancelGame').onclick=closeGame;$('confirmGame').onclick=addGame;$('gameName').oninput=e=>{if(game!==null){games[game].name=e.target.value;save();renderGames();$('pageTitle').textContent=e.target.value}};$('deleteGame').onclick=()=>{if(game!==null&&confirm('¿Eliminar este juego y todos sus Bosses?')){games.splice(game,1);save();game=null;$('gameEditor').hidden=true;$('gamesEmpty').hidden=false;$('pageTitle').textContent='Elige tu juego';renderGames()}};$('newBoss').onclick=showBossModal;$('closeBossModal').onclick=closeBoss;$('cancelBoss').onclick=closeBoss;$('confirmBoss').onclick=createBoss;document.querySelectorAll('#bossTypeChoices button').forEach(x=>x.onclick=()=>{bossType=x.dataset.type;document.querySelectorAll('#bossTypeChoices button').forEach(y=>y.classList.toggle('selected',y===x))});$('bossImage').onchange=e=>readImage(e.target.files[0],d=>{image=d;$('imagePreview').innerHTML=`<img src="${d}" alt="Vista previa">`});$('gameModal').addEventListener('click',e=>{if(e.target===$('gameModal'))closeGame()});$('bossModal').addEventListener('click',e=>{if(e.target===$('bossModal'))closeBoss()});
fillGames();renderGames();if(games.length)selectGame(0);else{$('gamesEmpty').hidden=false;$('gameEditor').hidden=true}load();